export const APPLICATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  NEEDS_INFORMATION: 'NEEDS_INFORMATION',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

export const APPLICATION_STATUS_LIST = Object.values(APPLICATION_STATUS);
