export const AUDIT_ACTIONS = Object.freeze({
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',

  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  APPLICATION_INFORMATION_REQUESTED: 'APPLICATION_INFORMATION_REQUESTED',

  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',

  LICENSE_ISSUED: 'LICENSE_ISSUED',
  LICENSE_REVOKED: 'LICENSE_REVOKED',
});

export const AUDIT_ACTION_LIST = Object.values(AUDIT_ACTIONS);
