export const DOCUMENT_TYPES = Object.freeze({
  EDUCATION_CERTIFICATE: 'EDUCATION_CERTIFICATE',
  CRIMINAL_RECORD: 'CRIMINAL_RECORD',
  BUSINESS_REGISTRATION: 'BUSINESS_REGISTRATION',
});

export const DOCUMENT_TYPE_LIST = Object.values(DOCUMENT_TYPES);
