export const NOTIFICATION_TYPES = Object.freeze({
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_UNDER_REVIEW: 'APPLICATION_UNDER_REVIEW',
  APPLICATION_NEEDS_INFORMATION: 'APPLICATION_NEEDS_INFORMATION',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  LICENSE_ISSUED: 'LICENSE_ISSUED',
});

export const NOTIFICATION_TYPE_LIST = Object.values(NOTIFICATION_TYPES);
